# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f347e9c6b60f26156b0e4b840acf60dd3d21f3e18860ec834d276d85d86bdca7ef9977c20102737c612a7b3b9d3e4a3e0189b2d5e17cb9d26027f27be3b84f77

test:
  secret_key_base: 6d81d59a06e088586030d409a5e80ce95adf9cc54460b9a5ca4a4018b50a653488e7898a08769803e00ae2245f0e2403e060de3ee248c8325b3cc0e56c5a2afb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
